"""empty message

Revision ID: 829ec04c56bf
Revises: 
Create Date: 2021-01-31 22:41:36.391018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '829ec04c56bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calculated_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('split', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('min_loss_f1', sa.Float(), nullable=True),
    sa.Column('min_loss_accuracy', sa.Float(), nullable=True),
    sa.Column('min_loss_test_acc', sa.Float(), nullable=True),
    sa.Column('min_loss_test_loss', sa.Float(), nullable=True),
    sa.Column('max_acc_f1', sa.Float(), nullable=True),
    sa.Column('max_acc_accuracy', sa.Float(), nullable=True),
    sa.Column('max_acc_test_acc', sa.Float(), nullable=True),
    sa.Column('max_acc_test_loss', sa.Float(), nullable=True),
    sa.Column('averaged_test_f1', sa.Float(), nullable=True),
    sa.Column('averaged_test_accuracy', sa.Float(), nullable=True),
    sa.Column('averaged_test_loss', sa.Float(), nullable=True),
    sa.Column('averaged_holdout_f1', sa.Float(), nullable=True),
    sa.Column('averaged_holdout_accuracy', sa.Float(), nullable=True),
    sa.Column('averaged_holdout_loss', sa.Float(), nullable=True),
    sa.Column('hyperparameters', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('input_form', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('split_uuid', sa.String(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('train_data_stats', sa.String(), nullable=True),
    sa.Column('validation_data_stats', sa.String(), nullable=True),
    sa.Column('test_data_stats', sa.String(), nullable=True),
    sa.Column('train_accuracy', sa.Float(), nullable=True),
    sa.Column('train_loss', sa.Float(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('loss', sa.Float(), nullable=True),
    sa.Column('test_accuracy', sa.Float(), nullable=True),
    sa.Column('test_loss', sa.Float(), nullable=True),
    sa.Column('probabilities', sa.String(), nullable=True),
    sa.Column('labels', sa.String(), nullable=True),
    sa.Column('test_probabilities', sa.String(), nullable=True),
    sa.Column('test_labels', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('input_form', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('hyperparameters', sa.String(), nullable=True),
    sa.Column('history', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('x_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('split', sa.String(), nullable=True),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('fold', sa.Integer(), nullable=True),
    sa.Column('total_folds', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('train_data_stats', sa.String(), nullable=True),
    sa.Column('validation_data_stats', sa.String(), nullable=True),
    sa.Column('test_data_stats', sa.String(), nullable=True),
    sa.Column('holdout_test_data_stats', sa.String(), nullable=True),
    sa.Column('train_accuracy', sa.Float(), nullable=True),
    sa.Column('train_loss', sa.Float(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('loss', sa.Float(), nullable=True),
    sa.Column('test_accuracy', sa.Float(), nullable=True),
    sa.Column('test_loss', sa.Float(), nullable=True),
    sa.Column('holdout_test_accuracy', sa.Float(), nullable=True),
    sa.Column('holdout_test_loss', sa.Float(), nullable=True),
    sa.Column('probabilities', sa.String(), nullable=True),
    sa.Column('labels', sa.String(), nullable=True),
    sa.Column('test_probabilities', sa.String(), nullable=True),
    sa.Column('test_labels', sa.String(), nullable=True),
    sa.Column('holdout_test_probabilities', sa.String(), nullable=True),
    sa.Column('holdout_test_labels', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('input_form', sa.String(), nullable=True),
    sa.Column('label_form', sa.String(), nullable=True),
    sa.Column('hyperparameters', sa.String(), nullable=True),
    sa.Column('history', sa.String(), nullable=True),
    sa.Column('test_f1_result', sa.Float(), nullable=True),
    sa.Column('holdout_f1_result', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('x_result')
    op.drop_table('result')
    op.drop_table('calculated_result')
    # ### end Alembic commands ###
